<a href="https://colab.research.google.com/github/andreunilux/BSP_6/blob/main/Concat_Gold_and_silver_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Pandas Dataframe Library
import json
import pandas as pd
import os
from IPython.display import display
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
os.getcwd()
os.chdir('/content/drive/MyDrive/BSP6/init_dataset_gold')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
train_data_gold = pd.read_json('train.json', lines=True)
val_data_gold = pd.read_json('val.json', lines=True)
test_data_gold = pd.read_json('test.json', lines=True)


os.chdir('/content/drive/MyDrive/BSP6/init_dataset_silver')   

train_data_silver = pd.read_json('train.json', lines=True)
val_data_silver = pd.read_json('val.json', lines=True)

In [ ]:
display(train_data_gold.describe())
display(val_data_gold.describe())
display(train_data_gold.head())

               idx        label
count  3325.000000  3325.000000
mean   1662.000000     0.956090
std     959.989149     0.713373
min       0.000000     0.000000
25%     831.000000     0.000000
50%    1662.000000     1.000000
75%    2493.000000     1.000000
max    3324.000000     2.000000

              idx       label
count  713.000000  713.000000
mean   356.000000    0.934081
std    205.969658    0.705020
min      0.000000    0.000000
25%    178.000000    0.000000
50%    356.000000    1.000000
75%    534.000000    1.000000
max    712.000000    2.000000

,idx,label,context,target
0,0,2,The UK is fucked.,>The ~~UK~~ world is fucked FTFY
1,1,0,Listen to this wisdom.,Where the Fuck did you get that up arrow?
2,2,1,"""That's different.""",You're right. The ultrasound says it's a girl....
3,3,2,"Oh fuck offffff, this is just patently untrue ...",Lol you can always spot a valid arguement when...
4,4,2,This whole sub should come to terms with reali...,I stopped reading your history after you wante...

In [ ]:
display(train_data_silver.head())
train_data_silver['idx']=train_data_silver['idx'].apply(lambda x: x+3325)
display(train_data_silver.head())
val_data_silver['idx']=val_data_silver['idx'].apply(lambda x: x+714)

,idx,label,target,context
0,0,1,"This is reddit, you’re allowed to see assholes...",All I see is >a$$#@!#$
1,1,2,Are you seriously complaining about not buying...,What makes me mad is when I try to find an exi...
2,2,2,"> Democrats Uhh, you know that American poli...",Ugh. Fucking ridiculous. Literally there for t...
3,3,1,Gotta have money to drink,Talk about injustice. I can't even imagine w...
4,4,0,Yup everyone has the kill whitey it’s whiteys ...,"to be fair, it's acceptable to praise males if..."

,idx,label,target,context
0,3325,1,"This is reddit, you’re allowed to see assholes...",All I see is >a$$#@!#$
1,3326,2,Are you seriously complaining about not buying...,What makes me mad is when I try to find an exi...
2,3327,2,"> Democrats Uhh, you know that American poli...",Ugh. Fucking ridiculous. Literally there for t...
3,3328,1,Gotta have money to drink,Talk about injustice. I can't even imagine w...
4,3329,0,Yup everyone has the kill whitey it’s whiteys ...,"to be fair, it's acceptable to praise males if..."

In [ ]:
train_data_gold_and_silver=pd.concat([train_data_gold ,train_data_silver],ignore_index=True)
train_data_gold_and_silver.iloc[3325]
val_data_gold_and_silver=pd.concat([val_data_gold ,val_data_silver],ignore_index=True)
val_data_gold_and_silver.iloc[714]
train_data_gold_and_silver

,idx,label,context,target
0,0,2,The UK is fucked.,>The ~~UK~~ world is fucked FTFY
1,1,0,Listen to this wisdom.,Where the Fuck did you get that up arrow?
2,2,1,"""That's different.""",You're right. The ultrasound says it's a girl....
3,3,2,"Oh fuck offffff, this is just patently untrue ...",Lol you can always spot a valid arguement when...
4,4,2,This whole sub should come to terms with reali...,I stopped reading your history after you wante...
...,...,...,...,...
4995,4995,2,except the guy did keep touching her boobs aft...,I think stabbing someone is a little worse...
4996,4996,2,"""Look, I really don't like that person, so eve...",> everything they say is automatically false ...
4997,4997,2,Why kill yourself when you can kill both of them?,Or just ghost them all
4998,4998,0,"Yeah, with guys mug shots are all stained wif...",Yeah they posted her fucking duckface instagra...
4999,4999,1,"Eh, the movement has been coopted. I call myse...",Hey. Thanks for recognizing a difficult truth....

In [ ]:
train_data_gold_and_silver.to_json(r'/content/drive/MyDrive/BSP6/init_dataset_gold_silver/train.json', orient='records', lines=True)
val_data_gold_and_silver.to_json(r'/content/drive/MyDrive/BSP6/init_dataset_gold_silver/val.json', orient='records' ,lines=True)
os.getcwd()

'/content/drive/MyDrive/BSP6/init_dataset_silver'